#!/bin/bash

NAME=`echo $PWD | sed 's!/!_!gi'`

docker rm $NAME

docker run -it \
  -v /etc/localtime:/etc/localtime:ro \
  -v "${PWD}:/logs" \
  -e TERM=xterm-256color \
  --name lnav_${NAME} \
  lnav

#docker rm lnav_${NAME}
