#!/bin/bash

NAME=`echo lnav_$PWD | sed 's!/!_!gi'`

docker rm $NAME

docker run -it \
  -v /etc/localtime:/etc/localtime:ro \
  -v "${PWD}:/logs" \
  -e TERM=xterm-256color \
  --name ${NAME} \
  lnav

docker rm ${NAME}
