#!/bin/bash

docker rm thunderbird

DBUS_PATH=$(echo ${DBUS_SESSION_BUS_ADDRESS} | cut -d = -f 2)
echo $DBUS_PATH
docker run \
  -v "${HOME}/.thunderbird:/home/thunderbird/.thunderbird" \
  -v "${HOME}/Downloads:/home/thunderbird/Downloads" \
  -v /etc/localtime:/etc/localtime:ro \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  --env="DBUS_SESSION_BUS_ADDRESS" \
  --volume=${DBUS_PATH}:${DBUS_PATH} \
  -e DISPLAY=unix$DISPLAY \
  --name thunderbird \
  thunderbird
