#!/bin/bash

docker rm abricotine

docker run -d \
  -v /etc/localtime:/etc/localtime:ro \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -v "${HOME}/Documents:/data" \
  -e DISPLAY=unix$DISPLAY \
  --name abricotine \
  abricotine
