#!/bin/bash

docker rm yakyak

docker run -d \
  -v /etc/localtime:/etc/localtime:ro \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -v "$HOME/.config/yakyak:/home/yakyak/.config/yakyak" \
  -e DISPLAY=unix$DISPLAY \
  --name yakyak \
  yakyak
